Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, :path => "bootstrap.sh"

  # copy keys from dropbox
  config.vm.provision "file", source: "~/Dropbox/keys/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "shell", inline: "chmod 0400 /home/vagrant/.ssh/id_rsa"
end
